version: '4.6.0-{build}-WuYang'

environment:
  ANDROID_HOME: C:\android-sdk-windows

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
  - 7z x sdk-tools-windows-4333796.zip -oC:\android-sdk-windows > nul
  - yes | C:\android-sdk-windows\tools\bin\sdkmanager.bat --licenses > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "platforms;android-28" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "platform-tools" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "build-tools;28.0.3" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "cmake;3.6.4111459" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "patcher;v4" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "ndk;22.0.7026061" --channel=1 > nul
  - set PATH=%PATH%;C:\android-sdk-windows\ndk-bundle;C:\android-sdk-windows\build-tools\28.0.3

build_script:
  - gradlew.bat build

artifacts:
  - path: 'app\build\outputs\apk\release\*.apk'
  - path: 'stub\build\outputs\apk\release\*.apk'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true
